apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    trains: webserver-service
    platform: trains
  namespace: trains
spec:
  selector:
    trains: webserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
  labels:
    trains: apiserver-service
    platform: trains
  namespace: trains
spec:
  selector:
    trains: apiserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 8008
    targetPort: 8008
    nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: fileserver-service
  labels:
    trains: fileserver-service
    platform: trains
  namespace: trains
spec:
  selector:
    trains: fileserver
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    trains: mongo-service
    platform: trains
  namespace: trains
spec:
  selector:
    trains: mongo
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  labels:
    trains: elasticsearch-service
    platform: trains
  namespace: trains
spec:
  selector:
    trains: elasticsearch
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
