apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    trains: webserver
    platform: trains
  name: webserver
  namespace: trains
spec:
  replicas: 1
  minReadySeconds: 15
  progressDeadlineSeconds: 180
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        trains: webserver
        platform: trains
    spec:
      containers:
      - image: allegroai/trains-server:0.10.1-1
        name: webserver
        args:
        - webserver
        volumeMounts:
        - mountPath: /var/log/trains
          name: webserver-hostpath
      restartPolicy: Always
      nodeSelector:
        app: trains
      volumes:
      - name: webserver-hostpath
        hostPath:
          path: /var/log/trains
