trains:
  nodeSelector: "app: trains"
  namespace: trains
  image:
    repository: allegroai/trains-server
    tag: 0.12.1-182
apiserver:
  elasticServiceName: elasticsearch-service
  elasticServicePort: "9200"
  mongoServiceName: mongo-service
  mongoServicePort: "27017"
  redisServiceName: redis
  redisServicePort: "6379"
  configDir: /opt/trains/config
  volumeMounts:
    - mountPath: /var/log/trains
      name: apiserver-hostpath0
    - mountPath: /opt/trains/config
      name: apiserver-hostpath1
  volumes:
    - name: apiserver-hostpath0
      hostPath:
        path: /opt/trains/logs
    - name: apiserver-hostpath1
      hostPath:
        path: /opt/trains/config
elasticsearch:
  esJavaOpts: "-Xms2g -Xmx2g"
services:
  webserver:
    nodePort: 30080
    name: webserver-service
  apiserver:
    nodePort: 30008
    name: apiserver-service
  fileserver:
    nodePort: 30081
    name: fileserver-service
  mongo:
    name: mongo-service
  elasticsearch:
    name: elasticsearch-service
  redis:
    name: redis
use_secrets_flexvolume: false